"""Lyria music-generation client with a deterministic mock fallback.

- If GEMINI_API_KEY is set AND google-genai is installed, calls the real
  Lyria 3 Pro model for an instrumental track.
- Otherwise, synthesizes a devotional-style instrumental locally so the whole
  pipeline runs today without any API key. The mock is deterministic (seeded)
  and matches the requested BPM / key / duration so alignment behaves like the
  real thing.

The rest of the app depends only on `generate_instrumental()`, so swapping in
the real API later changes nothing downstream (adapter pattern).
"""
from __future__ import annotations

import base64
import os
from dataclasses import dataclass

import numpy as np

from ..config import NOTE_FREQS, SAMPLE_RATE, TAAL_BEATS, BhajanSpec


@dataclass
class GenerationResult:
    audio_mono: np.ndarray      # float32 mono at SAMPLE_RATE
    sample_rate: int
    source: str                 # "lyria" | "mock"
    prompt: str
    notes: str = ""


def generate_instrumental(
    spec: BhajanSpec,
    prompt: str,
    duration_seconds: float,
    seed: int = 0,
) -> GenerationResult:
    """Generate an instrumental. Uses Lyria if available, else the mock."""
    if _lyria_available():
        try:
            return _generate_with_lyria(prompt, duration_seconds)
        except Exception as exc:  # pragma: no cover - network path
            # Never hard-fail the pipeline; fall back to mock and record why.
            note = f"Lyria call failed ({exc}); used mock instrumental."
            res = _generate_mock(spec, prompt, duration_seconds, seed)
            res.notes = note
            return res
    return _generate_mock(spec, prompt, duration_seconds, seed)


def _lyria_available() -> bool:
    if not os.environ.get("GEMINI_API_KEY"):
        return False
    try:
        import google.genai  # noqa: F401
        return True
    except Exception:
        return False


def _generate_with_lyria(prompt: str, duration_seconds: float) -> GenerationResult:
    """Call the real Lyria 3 Pro model (requires GEMINI_API_KEY).

    Lyria accepts text/image only and returns audio; we request a WAV so we can
    decode it directly. Kept minimal and behind the same interface as the mock.
    """
    import io as _io

    import soundfile as _sf
    from google import genai

    client = genai.Client()
    full_prompt = f"{prompt} Create an approximately {round(duration_seconds)}-second track."
    interaction = client.interactions.create(
        model="lyria-3-pro-preview",
        input=full_prompt,
        response_format={"type": "audio"},
    )
    audio_block = interaction.output_audio
    if not audio_block or not getattr(audio_block, "data", None):
        raise RuntimeError("Lyria returned no audio data")

    raw = base64.b64decode(audio_block.data)
    data, sr = _sf.read(_io.BytesIO(raw), dtype="float32", always_2d=True)
    mono = data.mean(axis=1).astype(np.float32)
    return GenerationResult(
        audio_mono=mono,
        sample_rate=sr,
        source="lyria",
        prompt=full_prompt,
        notes="Generated by Lyria 3 Pro. Note: audio carries a SynthID watermark.",
    )


# --------------------------------------------------------------------------
# Mock devotional instrument synthesizer (deterministic, dependency-light)
# --------------------------------------------------------------------------

def _generate_mock(
    spec: BhajanSpec, prompt: str, duration_seconds: float, seed: int
) -> GenerationResult:
    rng = np.random.default_rng(seed)
    sr = SAMPLE_RATE
    n = int(max(1.0, duration_seconds) * sr)
    t = np.arange(n) / sr

    tonic = NOTE_FREQS.get(spec.key.strip().capitalize(), 261.63)
    fifth = tonic * 1.5
    third = tonic * (5.0 / 4.0)  # just major third, warm harmonium colour

    mix = np.zeros(n, dtype=np.float32)

    # 1) Tanpura-style drone: tonic + fifth, slightly detuned, slow shimmer.
    for f, amp in ((tonic, 0.18), (fifth, 0.12), (tonic * 2, 0.06)):
        detune = 1.0 + rng.uniform(-0.001, 0.001)
        shimmer = 1.0 + 0.02 * np.sin(2 * np.pi * 0.15 * t)
        mix += amp * shimmer * np.sin(2 * np.pi * f * detune * t)

    # 2) Harmonium-style pad: tonic-third-fifth chord with a few harmonics.
    for f in (tonic, third, fifth):
        for h, hamp in ((1, 0.10), (2, 0.04), (3, 0.02)):
            mix += hamp * np.sin(2 * np.pi * f * h * t + rng.uniform(0, 6.28))

    # 3) Percussion (tabla/dholak) on the taal grid.
    beats_per_bar = TAAL_BEATS.get(spec.taal.lower(), 8)
    sec_per_beat = 60.0 / max(1.0, spec.bpm)
    perc = np.zeros(n, dtype=np.float32)
    beat_idx = 0
    tcur = 0.0
    while tcur < duration_seconds:
        start = int(tcur * sr)
        accent = (beat_idx % beats_per_bar) in (0, beats_per_bar // 2)
        perc += _perc_hit(n, start, sr, accent=accent)
        beat_idx += 1
        tcur += sec_per_beat
    mix += 0.5 * perc

    # 4) Gentle fade in/out so intro/outro are clean (helps QC).
    mix = _apply_fades(mix, sr, fade_in=1.0, fade_out=1.5)

    # Normalise to a safe working level (mastering happens later).
    peak = float(np.max(np.abs(mix))) or 1.0
    mix = (mix / peak * 0.6).astype(np.float32)

    return GenerationResult(
        audio_mono=mix,
        sample_rate=sr,
        source="mock",
        prompt=prompt,
        notes="Synthetic devotional instrumental (no API key / offline mode).",
    )


def _perc_hit(n: int, start: int, sr: int, accent: bool) -> np.ndarray:
    """A short pitched thump to stand in for tabla/dholak."""
    dur = int(0.18 * sr)
    end = min(n, start + dur)
    if start >= n or end <= start:
        return np.zeros(n, dtype=np.float32)
    length = end - start
    tt = np.arange(length) / sr
    freq = 180.0 if accent else 120.0
    env = np.exp(-tt * (18.0 if accent else 26.0))
    tone = np.sin(2 * np.pi * freq * tt) * env
    out = np.zeros(n, dtype=np.float32)
    out[start:end] = (0.9 if accent else 0.6) * tone
    return out


def _apply_fades(x: np.ndarray, sr: int, fade_in: float, fade_out: float) -> np.ndarray:
    n = x.size
    fi = min(int(fade_in * sr), n // 2)
    fo = min(int(fade_out * sr), n // 2)
    if fi > 0:
        x[:fi] *= np.linspace(0.0, 1.0, fi)
    if fo > 0:
        x[-fo:] *= np.linspace(1.0, 0.0, fo)
    return x
