"""Lyria music-generation client (live REST) with a deterministic mock fallback.

Auth: Lyria is reached through the Gemini API `interactions` endpoint using an
API key sent as the `x-goog-api-key` header (validated against the live API).
The key is read from the environment - NEVER hard-coded:

    BHAJAN_API_KEY  (preferred)  |  GEMINI_API_KEY  |  GOOGLE_API_KEY

Behaviour:
- If a key is present, we call Lyria 3 Pro for an instrumental track.
- On ANY failure (no key, quota 429, network, parse) we fall back to a local
  deterministic devotional instrumental so the pipeline never hard-fails and
  the whole product remains testable offline.

The rest of the app depends only on `generate_instrumental()` /
`generate_candidates()`, so the live/mock swap is invisible downstream.
"""
from __future__ import annotations

import base64
import json
import os
import urllib.error
import urllib.request
from dataclasses import dataclass

import numpy as np

from ..config import NOTE_FREQS, SAMPLE_RATE, TAAL_BEATS, BhajanSpec

LYRIA_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/interactions"
LYRIA_MODEL = "lyria-3-pro-preview"
_KEY_ENV_VARS = ("BHAJAN_API_KEY", "GEMINI_API_KEY", "GOOGLE_API_KEY")


@dataclass
class GenerationResult:
    audio_mono: np.ndarray      # float32 mono at SAMPLE_RATE
    sample_rate: int
    source: str                 # "lyria" | "mock"
    prompt: str
    notes: str = ""


def get_api_key() -> str | None:
    for var in _KEY_ENV_VARS:
        val = os.environ.get(var)
        if val:
            return val
    return None


def live_probe(timeout: float = 20.0) -> dict:
    """Lightweight check of whether the live Lyria endpoint is usable.

    Returns a dict: {enabled, ok, status, detail}. Does a real (small) request
    only when a key is configured. Safe to call from a health endpoint.
    """
    key = get_api_key()
    if not key:
        return {"enabled": False, "ok": False, "status": None,
                "detail": "No API key configured (mock mode)."}
    try:
        _call_lyria("A short devotional harmonium instrumental.", key, timeout)
        return {"enabled": True, "ok": True, "status": 200, "detail": "Lyria reachable."}
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", "ignore")[:200]
        detail = "Lyria quota not available (429)." if e.code == 429 else body
        return {"enabled": True, "ok": False, "status": e.code, "detail": detail}
    except Exception as e:  # pragma: no cover
        return {"enabled": True, "ok": False, "status": None, "detail": str(e)}


def generate_instrumental(spec: BhajanSpec, prompt: str, duration_seconds: float,
                          seed: int = 0) -> GenerationResult:
    """Generate one instrumental. Live Lyria if possible, else mock."""
    key = get_api_key()
    if key:
        try:
            mono, sr = _call_lyria(_with_duration(prompt, duration_seconds), key)
            return GenerationResult(
                mono, sr, "lyria", prompt,
                "Generated by Lyria 3 Pro (audio carries an inaudible SynthID watermark).",
            )
        except urllib.error.HTTPError as e:
            note = _http_note(e)
        except Exception as e:  # pragma: no cover
            note = f"Lyria call failed ({e}); used mock instrumental."
        res = _generate_mock(spec, prompt, duration_seconds, seed)
        res.notes = note
        return res
    return _generate_mock(spec, prompt, duration_seconds, seed)


def generate_candidates(spec: BhajanSpec, prompt: str, duration_seconds: float,
                        n: int = 3, seed: int = 0) -> list[GenerationResult]:
    """Generate N candidate instrumentals for the human-selection gate."""
    return [
        generate_instrumental(spec, prompt, duration_seconds, seed=seed + i)
        for i in range(max(1, n))
    ]


# --------------------------------------------------------------------------
# Live Lyria (REST)
# --------------------------------------------------------------------------

def _with_duration(prompt: str, duration_seconds: float) -> str:
    return f"{prompt} Create an approximately {round(duration_seconds)}-second track."


def _http_note(e: urllib.error.HTTPError) -> str:
    if e.code == 429:
        return ("Lyria returned 429 (no quota on this key); used mock. "
                "Enable Lyria billing to switch to live audio.")
    return f"Lyria HTTP {e.code}; used mock instrumental."


def _call_lyria(prompt: str, key: str, timeout: float = 120.0) -> tuple[np.ndarray, int]:
    """POST to the Lyria interactions endpoint and return (mono_float32, sr)."""
    payload = json.dumps({
        "model": LYRIA_MODEL,
        "input": prompt,
        "response_format": {"type": "audio"},
    }).encode("utf-8")
    req = urllib.request.Request(
        LYRIA_ENDPOINT, data=payload, method="POST",
        headers={"Content-Type": "application/json", "x-goog-api-key": key},
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    b64 = _extract_audio_b64(data)
    if not b64:
        raise RuntimeError("Lyria response contained no audio block")
    return _decode_audio_b64(b64)


def _extract_audio_b64(data: dict) -> str | None:
    # Convenience field first, then walk the steps schema.
    out = data.get("output_audio") or {}
    if isinstance(out, dict) and out.get("data"):
        return out["data"]
    for step in data.get("steps", []):
        if step.get("type") != "model_output":
            continue
        for block in step.get("content", []):
            if block.get("type") == "audio" and block.get("data"):
                return block["data"]
    return None


def _decode_audio_b64(b64: str) -> tuple[np.ndarray, int]:
    import io as _io

    import soundfile as _sf
    raw = base64.b64decode(b64)
    audio, sr = _sf.read(_io.BytesIO(raw), dtype="float32", always_2d=True)
    return audio.mean(axis=1).astype(np.float32), int(sr)


# --------------------------------------------------------------------------
# Mock devotional instrument synthesizer (deterministic, dependency-light)
# --------------------------------------------------------------------------

def _generate_mock(spec: BhajanSpec, prompt: str, duration_seconds: float,
                   seed: int) -> GenerationResult:
    rng = np.random.default_rng(seed)
    sr = SAMPLE_RATE
    n = int(max(1.0, duration_seconds) * sr)
    t = np.arange(n) / sr

    tonic = NOTE_FREQS.get(spec.key.strip().capitalize(), 261.63)
    fifth = tonic * 1.5
    third = tonic * (5.0 / 4.0)

    mix = np.zeros(n, dtype=np.float32)

    # Tanpura-style drone.
    for f, amp in ((tonic, 0.18), (fifth, 0.12), (tonic * 2, 0.06)):
        detune = 1.0 + rng.uniform(-0.001, 0.001)
        shimmer = 1.0 + 0.02 * np.sin(2 * np.pi * 0.15 * t)
        mix += amp * shimmer * np.sin(2 * np.pi * f * detune * t)

    # Harmonium-style pad.
    for f in (tonic, third, fifth):
        for h, hamp in ((1, 0.10), (2, 0.04), (3, 0.02)):
            mix += hamp * np.sin(2 * np.pi * f * h * t + rng.uniform(0, 6.28))

    # Percussion on the taal grid.
    beats_per_bar = TAAL_BEATS.get(spec.taal.lower(), 8)
    sec_per_beat = 60.0 / max(1.0, spec.bpm)
    perc = np.zeros(n, dtype=np.float32)
    beat_idx = 0
    tcur = 0.0
    while tcur < duration_seconds:
        start = int(tcur * sr)
        accent = (beat_idx % beats_per_bar) in (0, beats_per_bar // 2)
        perc += _perc_hit(n, start, sr, accent=accent)
        beat_idx += 1
        tcur += sec_per_beat
    mix += 0.5 * perc

    mix = _apply_fades(mix, sr, fade_in=1.0, fade_out=1.5)
    peak = float(np.max(np.abs(mix))) or 1.0
    mix = (mix / peak * 0.6).astype(np.float32)

    return GenerationResult(
        mix, sr, "mock", prompt,
        "Synthetic devotional instrumental (offline / no Lyria quota).",
    )


def _perc_hit(n: int, start: int, sr: int, accent: bool) -> np.ndarray:
    dur = int(0.18 * sr)
    end = min(n, start + dur)
    if start >= n or end <= start:
        return np.zeros(n, dtype=np.float32)
    length = end - start
    tt = np.arange(length) / sr
    freq = 180.0 if accent else 120.0
    env = np.exp(-tt * (18.0 if accent else 26.0))
    tone = np.sin(2 * np.pi * freq * tt) * env
    out = np.zeros(n, dtype=np.float32)
    out[start:end] = (0.9 if accent else 0.6) * tone
    return out


def _apply_fades(x: np.ndarray, sr: int, fade_in: float, fade_out: float) -> np.ndarray:
    n = x.size
    fi = min(int(fade_in * sr), n // 2)
    fo = min(int(fade_out * sr), n // 2)
    if fi > 0:
        x[:fi] *= np.linspace(0.0, 1.0, fi)
    if fo > 0:
        x[-fo:] *= np.linspace(1.0, 0.0, fo)
    return x
